apiVersion: apps/v1
kind: Deployment
metadata:
  name: dissertation-ai
  namespace : bits-dissertation-86314
  annotations:
    argocd-image-updater.argoproj.io/image-list: bits2025.azurecr.io/bits-pilani-dissertation-ai
    argocd-image-updater.argoproj.io/bits2025.azurecr.io/bits-pilani-dissertation-ai.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dissertation-ai
  template:
    metadata:
      labels:
        app: dissertation-ai
    spec:
      containers:
      - name: dissertation-ai
        image: bits2025.azurecr.io/bits-pilani-dissertation-ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: azure-bits-test-local
